# Generated by Django 4.1.5 on 2023-01-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_chapter_options_alter_theme_options_theme_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='number',
            field=models.IntegerField(verbose_name='Номер главы'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='number',
            field=models.IntegerField(verbose_name='Номер темы'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='slug',
            field=models.SlugField(help_text='Отображается в url поле в верху браузера', null=True, unique=True, verbose_name='Ссылка'),
        ),
    ]
