# Generated by Django 4.1.5 on 2023-01-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_chapter_number_alter_theme_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='text',
            field=models.TextField(null=True, verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название главы'),
        ),
    ]
